name: Update progress

on:
  push:
    branches:
      - main
    paths:
      - 'src/*.c'
      - 'src/*.cpp'
      - 'src/**/*.c'
      - 'src/**/*.cpp'
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v2
      - name: Clone asset repository
        uses: actions/checkout@v2
        with:
          ref: 'gh-report'
          path: 'gh-report'
      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Generate report
        run: |
            python tools/report_progress.py
      - name: Commit report
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m 'Update progress' || true
            git push
        working-directory: gh-report